baseURL = "https://carloshs92.github.io/research-insight"
languageCode = "en-us"
title = "Innovation Project"
theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "Nosotros"
    URL = "about2"
    weight = 1

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 2

    [[menu.nav]]
    name = "Multimedia"
    URL = "portfolio"
    weight = 3

# Site params
[params]
home= "Inicio"
logo = "images/logo.png"

# Banner Section
[params.banner]
enable = true
bgImage = "images/banner.jpg"
icon = "tf-pencil2"
heading = "Metodologías Ágiles para la Innovación I"
content= "Estudio de la experiencia en la entrega de comida en el patio de comidas de Real Plaza Salaverry"
btn = false
